name: Lint

on:
 push:
   branches:
     - main
   tags: "*"
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox
        run: pip install tox
      - name: Check style
        run: tox -e style
